name: notebook
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - gdal
  - proj
  - geos
  - libgdal
  - rasterio
  - numpy
  - scipy
  - geopandas
  - shapely
  - matplotlib
  - tqdm
  - boto3
  - duckdb
  - pip:
      - earthaccess>=0.16.0
      - osmnx>=2.0.2
      - pystac-client>=0.9.0
      - typer>=0.15.3
      - obstore>=0.8.2
