"""Type stubs for pyproj.crs."""

from typing import Any

class CRS:
    """Coordinate Reference System."""

    def __init__(self, proj_string: str | dict[str, Any] | CRS | None = None) -> None: ...
    @classmethod
    def from_epsg(cls, code: int) -> CRS: ...
    @classmethod
    def from_string(cls, proj_string: str) -> CRS: ...
    @classmethod
    def from_dict(cls, proj_dict: dict[str, Any]) -> CRS: ...
    @classmethod
    def from_user_input(cls, value: Any) -> CRS: ...
    def to_wkt(self, pretty: bool = False) -> str: ...
    def to_proj4(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_epsg(self) -> int | None: ...
    @property
    def area_of_use(self) -> Any | None: ...
    @property
    def ellipsoid(self) -> Any | None: ...
    @property
    def is_geographic(self) -> bool: ...
    @property
    def is_projected(self) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

__all__ = ["CRS"]
