"""Type stubs for rasterio.crs."""

from typing import Any

class CRS:
    """Coordinate reference system."""

    def __init__(self, initialdata: Any = None, **kwargs: Any) -> None: ...
    @classmethod
    def from_epsg(cls, code: int) -> CRS: ...
    @classmethod
    def from_string(cls, value: str) -> CRS: ...
    @classmethod
    def from_proj4(cls, proj: str) -> CRS: ...
    @classmethod
    def from_wkt(cls, wkt: str) -> CRS: ...
    @classmethod
    def from_user_input(cls, value: Any, **kwargs: Any) -> CRS: ...
    def to_epsg(self) -> int | None: ...
    def to_string(self) -> str: ...
    def to_wkt(self) -> str: ...
    def to_proj4(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def is_geographic(self) -> bool: ...
    @property
    def is_projected(self) -> bool: ...
    @property
    def is_valid(self) -> bool: ...
    @property
    def linear_units(self) -> str: ...
    @property
    def units_factor(self) -> tuple[float, float]: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

__all__ = ["CRS"]
