"""Type stubs for rasterio.io."""

from typing import Any, Literal, overload

import numpy.typing as npt

from . import Profile
from .windows import Window

class MemoryFile:
    """A file-like object backed by an in-memory buffer."""
    def __init__(self, file_or_bytes: bytes | None = None) -> None: ...
    def __enter__(self) -> MemoryFile: ...
    def __exit__(self, *args: Any) -> None: ...
    @overload
    def open(self, mode: Literal["r"] = ..., **kwargs: Any) -> DatasetReader: ...
    @overload
    def open(self, mode: Literal["w", "w+", "r+"], **kwargs: Any) -> DatasetWriter: ...
    def close(self) -> None: ...
    def getbuffer(self) -> memoryview: ...
    @property
    def closed(self) -> bool: ...

class DatasetBase:
    """Base class for dataset readers and writers."""
    @property
    def count(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def bounds(self) -> tuple[float, float, float, float]: ...
    @property
    def transform(self) -> Any: ...
    @property
    def crs(self) -> Any: ...
    @property
    def meta(self) -> dict[str, Any]: ...
    @property
    def profile(self) -> Profile: ...
    @property
    def dtypes(self) -> list[str]: ...
    @property
    def nodata(self) -> float | None: ...
    def __enter__(self) -> DatasetBase: ...
    def __exit__(self, *args: Any) -> None: ...
    def read(
        self,
        indexes: int | list[int] | None = ...,
        out: npt.NDArray[Any] | None = ...,
        window: Window | None = ...,
        masked: bool = ...,
        out_shape: tuple[int, ...] | None = ...,
        resampling: Any = ...,
        fill_value: float | None = ...,
        out_dtype: Any | None = ...,
    ) -> npt.NDArray[Any]: ...
    def read_masks(
        self,
        indexes: int | list[int] | None = ...,
        out: npt.NDArray[Any] | None = ...,
        out_shape: tuple[int, ...] | None = ...,
        window: Window | None = ...,
        resampling: Any = ...,
    ) -> npt.NDArray[Any]: ...

class DatasetReader(DatasetBase):
    """A dataset opened in read mode."""

    def __enter__(self) -> DatasetReader: ...

    ...

class DatasetWriter(DatasetBase):
    """A dataset opened in write or update mode."""
    def __enter__(self) -> DatasetWriter: ...
    def write(
        self,
        arr: npt.NDArray[Any],
        indexes: int | list[int] | None = ...,
        window: Window | None = ...,
    ) -> None: ...
    def write_band(self, band: int, src: npt.NDArray[Any], window: Window | None = ...) -> None: ...
    def update_tags(self, bidx: int = ..., **kwargs: Any) -> None: ...
    def set_band_description(self, bidx: int, value: str) -> None: ...
    def set_band_unit(self, bidx: int, value: str) -> None: ...
    def build_overviews(self, factors: list[int], resampling: Any = ..., **kwargs: Any) -> None: ...

class BufferedDatasetWriter(DatasetWriter):
    """A dataset writer with internal buffer."""

    ...

__all__ = ["MemoryFile", "DatasetBase", "DatasetReader", "DatasetWriter", "BufferedDatasetWriter"]
